### PR TITLE
Add Galaxy Station wallet

### PR DESCRIPTION
**Pull request by echel0n-HX**
[comment]: <> (don't forget to run `yarn format` from the root :D)

### CODE REVIEW

**Comment by noahsaso** [comment]
hey thanks for this! is there a version of `@cosmos-kit/galaxy-station` that depends on `@cosmos-kit/core` version `2.10.0`? would rather not install multiple versions of the same package, and it may cause type issues

**Comment by echel0n-HX** [comment]
Good catch, I've submitted a PR to cosmos-kit to bump the version, once that happens I will then update this PR with the changes.

**Comment by echel0n-HX** [comment]
As requested, its been upgraded to use cosmos-kit v2.10.0

**Comment by noahsaso** [comment]
> As requested, its been upgraded to use cosmos-kit v2.10.0

actually now it looks to be using `v2.11.0` 😅 i'll push a commit updating the rest of the packages

**Review by noahsaso — APPROVED** [review]
thanks!

**Pull request merged**
