### PR TITLE
Open DAO in the same tab by default

### LINKED ISSUE #1310: Clicking a DAO should open in the same tab
Currently, clicking on a DAO in an inline link will open the link a different tab:

image

I think in-bound links should rarely if ever open in new tabs; regular navigation rules within the app should always navigate to the new page in the same tab.

If the intention here is to prevent the user from navigating away while editing, we might want to address that with a confirmation modal instead.

### PR DESCRIPTION
**Pull request by rishav-karanjit**
[comment]: <> (don't forget to run `yarn format` from the root :D)

Fixes #1310 

- Currently, clicking on a DAO in an inline link will open the link a different tab. This PR will disable opening link in different tab by default but allow us to manually override it.
- This PR adds an optional openInNewTab flag to EntityDisplayProps in packages/types/stateless/EntityDisplay.tsx
- Default openInNewTab to false in the component
- Then just pass it through to the ButtonLink directly

### CODE REVIEW

**Review by NoahSaso — CHANGES_REQUESTED** [review]
looks great! please add a description

**Comment by rishav-karanjit** [comment]
> looks great! please add a description

Just updated the description.

**Review by NoahSaso — APPROVED** [review]
looks goooood

**Comment by rishav-karanjit** [comment]
@NoahSaso can we close this PR to have the issue closed?

**Pull request merged**
