### PR TITLE
Add translation for zh-Hant (zh-tw)

### PR DESCRIPTION
**Pull request by PikachuEXE**
The translations in this PR would be reviewed by people I am going to gather.
This PR would be marked as not draft after enough reviews received.
Opening this PR early for anyone to put comment about specific translation entry(s).

For preview & review:
- https://dao-dao-ui-three.vercel.app
- https://dao-dao-ui-three.vercel.app/zh-tw (with new translation)

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Some entries update after review

However I spotted an issue (not applicable to English)

The voting choices "yes"/"no" is mixed with "yes"/"no" in option choice like `Allow revoting`

This is an issue for Chinese as in voting choices it should be `贊成/反對` (Approve/Oppose)
Option choice like `Allow revoting` should still be `是/否` (Yes/No)

I have no idea 
- Whether to resolve this issue in this PR
- How should this be resolved


image
image
image


Screenshot 2022-08-26 at 10 25 39
Screenshot 2022-08-26 at 10 25 42
Screenshot 2022-08-26 at 10 25 56

**Comment by PikachuEXE** [comment]
Already I have no idea how to handle that translation problem unless I get any feedback...
Don't want to make changes then get rejected...

**Comment by ezekiiel** [comment]
hey @PikachuEXE ! thanks so much for putting this together and sorry for the slow response. I've been away on vacation.

As far as resolving this goes - like you mention, the solution here is likely to split the current translation key into two options. Maybe `info.voteChoice` and `info.yesNo` (alternatively, we could just leave this as the existing key so that it requires less refactoring). For the existing translations we can leave it the same, and for this one we can split it into `贊成/反對 ` and `是/否 `, as you suggested.

Would you be OK making this change? Otherwise, I'm happy to merge this and push a followup commit to split those up.

**Comment by PikachuEXE** [comment]
[A test commit](https://github.com/PikachuEXE/dao-dao-ui/commit/e4116ce77fdcbbe1f4096f2d1fe36b498bd289d0) is pushed to create new entries for voting choices
The key names and depths can be adjusted if you wish
Only zh-tw & en files are updated for preview and other files will be updated once new structure confirmed

Please preview the changes at:
- https://dao-dao-ui-three.vercel.app
- https://dao-dao-ui-three.vercel.app/zh-tw

I have already checked the affected areas briefly

**Comment by NoahSaso** [comment]
> 

This looks great! I think it would be better to use `info.yes`/`info.yesVote`, `info.no`/`info.noVote`, and `info.abstainVote`, instead of creating a new top-level key. Could you make that change and push to this branch? Also run `yarn format` in the command line from the `i18n` package folder to sort the keys. so the linter is happy.

**Comment by PikachuEXE** [comment]
Changes committed to this PR and can be reviewed on
- https://dao-dao-ui-three.vercel.app/
- https://dao-dao-ui-three.vercel.app/zh-tw

However I discover another issue (and I have no idea how to fix this, just merge the PR if hard to fix)
image
image

**Comment by NoahSaso** [comment]
> Changes committed to this PR and can be reviewed on
> 
> * https://dao-dao-ui-three.vercel.app/
> * https://dao-dao-ui-three.vercel.app/zh-tw
> 
> However I discover another issue (and I have no idea how to fix this, just merge the PR if hard to fix) image image

Thanks! These changes are perfect.

Also great find. Looks like the css `ch` unit (width of `0` character in the current font) does not work very well across character sets... makes perfect sense. Luckily that component is only the place we were setting the width based on string length, so it's awesome you happened upon it and pointed it out. Pushed a fix :)

**Review by NoahSaso — APPROVED** [review]
Thank you so much!!

**Pull request merged**
