### PR TITLE
added Spanish translation

### PR DESCRIPTION
**Pull request by StarryHazex**
added Spanish translation

### CODE REVIEW

**Comment by ismellike** [comment]
LGTM - could fix a couple accents as well
```
"addAnAction": "Agregar una Acción",
"back": "Atrás"
```

**Comment by StarryHazex** [comment]
> LGTM - could fix a couple accents as well
> 
> ```
> "addAnAction": "Agregar una Acción",
> "back": "Atrás"
> ```

Processed

**Review by noahsaso — APPROVED** [review]
¡¡¡gracias!!!

**Comment by StarryHazex** [comment]
@NoahSaso  Apologies for the earlier issue with the i18n-json sorted-keys. The issue has been resolved. Please initiate a new merge check. Thank you.

**Pull request merged**
