### PR TITLE
Improved error text when simulating proposal actions fails

### PR DESCRIPTION
**Pull request by NoahSaso**
Made proposal action simulation failure error more specific.

Also removed `not found` from the common errors since it was potentially omitting information by replacing all errors that contain `not found` with `Not found.`

### CODE REVIEW

**Comment by 0xekez** [comment]
feel like the ux of checking the console is pretty sub optimal. can we show this error on the toast or on the page somewhere?

**Comment by NoahSaso** [comment]
> feel like the ux of checking the console is pretty sub optimal. can we show this error on the toast or on the page somewhere?

Agreed, I realized the error was being omitted because of the CommonError.NotFound enum that was too generally applying itself, so I removed it. The toast should show the full error message now, so I removed the browser console piece.

**Comment by 0xekez** [comment]
ah, probably "migrate method not found" or something. their contract likely just didn't export that.

**Review by 0xekez — APPROVED** [review]
:turbo:

**Pull request merged**
