### PR TITLE
Add an empty state for the proposal inbox

### PR DESCRIPTION
**Pull request by sagarsaija**
Old PR: https://github.com/DA0-DA0/dao-dao-ui/pull/892

Add the NoContent box for an empty proposal inbox:
Screen Shot 2022-11-15 at 6 25 08 PM

### CODE REVIEW

**Comment by NoahSaso** [comment]
Hmm I'm still not convinced this text is very accurate.

When there are pinned DAOs but no open proposals, this is what it looks like:
image

I think this view makes it pretty clear that it has checked all your DAOs and come up with nothing.

When there are no pinned DAOs, I think it is more accurate on this page to use the empty state from the pinned DAOs part of the home page:
image

because the reason their inbox is empty is _not_ that there are no proposals to vote on yet, there never will be if nothing changes. They first have to go through the steps of searching for a DAO and pinning some, which I think is good to encourage here.

@elsehow what do you think about these wording choices?

**Comment by elsehow** [comment]
I like the empty view @sagarsaija proposes, but agree the text could be improved. 

I might suggest:

> You're all caught up! There are no open proposals in any of your DAOs.

What do you think @sagarsaija @NoahSaso ?

Also, can someone remind me: in this inbox, are you going to see open proposals whether you've voted on them or not? I imagine yes - I imagine you'd want to follow open proposals (though the ones you've already voted on may be categorized into "already voted").

**Comment by NoahSaso** [comment]
> I like the empty view @sagarsaija proposes, but agree the text could be improved.
> 
> I might suggest:
> 
> > You're all caught up! There are no open proposals in any of your DAOs.
> 
> What do you think @sagarsaija @NoahSaso ?
> 
> Also, can someone remind me: in this inbox, are you going to see open proposals whether you've voted on them or not? I imagine yes - I imagine you'd want to follow open proposals (though the ones you've already voted on may be categorized into "already voted").

There are actually two views here:
- an empty page when you have pinned DAOs but no open proposals - an empty page when you have no pinned DAOs

do you think they should be the same?

**Comment by elsehow** [comment]
If you have no pinned DAOs, I'd say:

> You haven't pinned any DAOs! Pin some DAOs to follow open proposals.

If you have pinned DAOs, but no proposals are open, I'd say:

> You're all caught up! There are no open proposals in any of your pinned DAOs.

Side-note: I still hate this pinning thing. If you're a member of a DAO, you should follow it. Indexer should solve this in time.

**Comment by NoahSaso** [comment]
> If you have no pinned DAOs, I'd say:
> 
> > You haven't pinned any DAOs! Pin some DAOs to follow open proposals.
> 
> If you have pinned DAOs, but no proposals are open, I'd say:
> 
> > You're all caught up! There are no open proposals in any of your pinned DAOs.
> 
> Side-note: I still hate this pinning thing. If you're a member of a DAO, you should follow it. Indexer should solve this in time.

Love that. Sick. @sagarsaija you can use the `numOpenProposals` already defined for you to check for that second case there 😃

**Review by NoahSaso — APPROVED** [review]
Looks awesome, thank you!

Apologies for taking so long to review 🐑

**Pull request merged**
