### PR TITLE
Update to latest cosmos-kit versions and add more wallets

### PR DESCRIPTION
**Pull request by NoahSaso**
This adds support for:
- Metamask Snaps wallet
- Fin wallet
- OKX wallet

### CODE REVIEW

**Review by JakeHartnell — APPROVED** [review]
:fire:

**Comment by JakeHartnell** [comment]
Hmmmm... getting:
```
The method "wallet_requestSnaps" does not exist / is not available.
```

Maybe because snaps are only in development Metamask until later this month?

**Comment by JakeHartnell** [comment]
> Maybe because snaps are only in development Metamask until later this month?

If this is the case, it probably should be lower down the list?

**Comment by NoahSaso** [comment]
> Hmmmm... getting:
> 
> ```
> The method "wallet_requestSnaps" does not exist / is not available.
> ```
> 
> Maybe because snaps are only in development Metamask until later this month?

Yeah it doesn't work yet.

**Comment by NoahSaso** [comment]
> > Maybe because snaps are only in development Metamask until later this month?
> 
> If this is the case, it probably should be lower down the list?

I don't think we should merge this until it's ready.

**Pull request merged**
